name: build

on:
  push:
    branches:
      - main
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'

    - name: Set up uv
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv

    - name: Run the tests
      run: |
        bin/test.sh

    - name: Lint the code
      run: |
        bin/lint.sh
